#!/bin/bash

function print_prompt
{
	cat << CONFEOF
Usage: $0 [OPTION]... [VAR=VALUE]...

Configuration:
    --help                      display this help and exit
    --debug                     build for debug
    --build-demo                build demo
    --build-dir=DIR             build directory

Cross Compile:
    --toolchain=DIR             toolchain install dir
    --cross-prefix=PREFIX       compiler name prefix
    --cross-root-path=DIR       root dir for search dependencies libs
CONFEOF
}

builddir="build"

CMAKE_ARGS=
for conf_opt
do
	case $conf_opt in
		*=?*) conf_optarg=`expr "X$conf_opt" : '[^=]*=\(.*\)'` ;;
		*) conf_optarg= ;;
	esac

	case $conf_opt in
		--help)
			print_prompt
			exit 0
			;;
		--debug)
			CMAKE_ARGS=(${CMAKE_ARGS[@]} -DBUILD_DEBUG=ON)
			;;
		--build-demo)
			CMAKE_ARGS=(${CMAKE_ARGS[@]} -DBUILD_DEMO=ON)
			;;
		--build-dir=*)
			builddir=$conf_optarg
			;;
		--toolchain=*)
			CMAKE_ARGS=(${CMAKE_ARGS[@]} -DTOOLCHAIN_HOME=$conf_optarg)
			CROSS_COMPILE=yes
			;;
		--cross-prefix=*)
			CMAKE_ARGS=(${CMAKE_ARGS[@]} -DCROSS_PREFIX=$conf_optarg)
			;;
		--cross-root-path=*)
			CMAKE_ARGS=(${CMAKE_ARGS[@]} -DCROSS_ROOT_PATH=$conf_optarg)
			;;
	esac
done

if [ x$CROSS_COMPILE = x"yes" ]; then
CUR_DIR=`pwd`
CMAKE_ARGS=(${CMAKE_ARGS[@]} -DCMAKE_TOOLCHAIN_FILE=$CUR_DIR/cmake/toolchain.cmake)
fi

mkdir -p $builddir
cd $builddir
cmake .. \
	${CMAKE_ARGS[@]}
